version: "3.5"
services:
  app:
    ports:
      - ${DOCKER_APP_PORT}:${APP_PORT}
    command: ["npm", "run", "watch"]
  maria_db:
    ports:
      - 3306:3306
  maria_adminer:
    image: wodby/adminer:4.7
    container_name: maria-seq_adminer
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_DEFAULT_DB_HOST=maria_db
      - ADMINER_DEFAULT_DB_NAME=mariaseq
      - ADMINER_DESIGN=nette
    depends_on:
      - maria_db
    ports:
      - ${DOCKER_ADMINER_PORT}:9000
    networks:
      - maria-seq
